In [3]:
import pandas as pd
import json

In [5]:
df = pd.read_json("epl_2022_2023_07_02_2023.json", encoding="utf-8")
df.head(10)

,75091,75096,75098,75099,75093,75082,75088,75087,75089,75084,...,75127,75128,75129,75124,75125,75121,75122,75123,75126,75130
event,"[Full-time Match ends, Arsenal 0, Newcastle Un...","[Full-time Match ends, Everton 1, Brighton and...","[Full-time Match ends, Leicester City 0, Fulha...","[Full-time Match ends, Manchester United 3, Bo...","[Full-time Match ends, Brentford 3, Liverpool ...","[Full-time Match ends, Brighton and Hove Albio...","[Full-time Match ends, Tottenham Hotspur 0, As...","[Full-time Match ends, Nottingham Forest 1, Ch...","[Full-time Match ends, West Ham United 0, Bren...","[Full-time Match ends, Liverpool 2, Leicester ...",...,"[Full-time Match ends, Newcastle United 1, Wes...","[Full-time Match ends, Nottingham Forest 1, Le...","[Full-time Match ends, Tottenham Hotspur 1, Ma...","[Full-time Match ends, Chelsea 0, Fulham 0., S...","[Full-time Match ends, Everton 1, Arsenal 0., ...","[Full-time Match ends, Aston Villa 2, Leiceste...","[Full-time Match ends, Brentford 3, Southampto...","[Full-time Match ends, Brighton and Hove Albio...","[Full-time Match ends, Manchester United 2, Cr...","[Full-time Match ends, Wolverhampton Wanderers..."
matchweek,Matchweek 19,Matchweek 19,Matchweek 19,Matchweek 19,Matchweek 19,Matchweek 18,Matchweek 18,Matchweek 18,Matchweek 18,Matchweek 18,...,Matchweek 22,Matchweek 22,Matchweek 22,Matchweek 22,Matchweek 22,Matchweek 22,Matchweek 22,Matchweek 22,Matchweek 22,Matchweek 22
team1_name,Arsenal,Everton,Leicester City,Manchester United,Brentford,Brighton and Hove Albion,Tottenham Hotspur,Nottingham Forest,West Ham United,Liverpool,...,Newcastle United,Nottingham Forest,Tottenham Hotspur,Chelsea,Everton,Aston Villa,Brentford,Brighton & Hove Albion,Manchester United,Wolverhampton Wanderers
team1_startings,"[Aaron Ramsdale, Ben White, Gabriel Magalhães,...","[Jordan Pickford, James Tarkowski, Nathan Patt...","[Danny Ward, Wout Faes, Daniel Amartey, Timoth...","[David de Gea, Victor Lindelöf, Harry Maguire,...","[David Raya, Ethan Pinnock, Zanka, Ben Mee, Ri...","[Robert Sánchez, Tariq Lamptey, Lewis Dunk, Le...","[Hugo Lloris, Cristian Romero, Ben Davies, Clé...","[Dean Henderson, Joe Worrall, Serge Aurier, Wi...","[Lukasz Fabianski, Aaron Cresswell, Craig Daws...","[Alisson, Virgil van Dijk, Andrew Robertson, J...",...,"[Nick Pope, Kieran Trippier, Sven Botman, Fabi...","[Keylor Navas, Neco Williams, Scott McKenna, W...","[Hugo Lloris, Eric Dier, Cristian Romero, Ben ...","[Kepa Arrizabalaga, Benoît Badiashile, Thiago ...","[Jordan Pickford, James Tarkowski, Vitaliy Myk...","[Emiliano Martínez, Ezri Konsa, Tyrone Mings, ...","[David Raya, Aaron Hickey, Rico Henry, Ethan P...","[Robert Sánchez, Lewis Dunk, Pervis Estupiñán,...","[David de Gea, Lisandro Martínez, Raphaël Vara...","[José Sá, Rayan Aït-Nouri, Craig Dawson, Nélso..."
team1_subs,"[Matt Turner, Kieran Tierney, Rob Holding, Tak...","[Asmir Begovic, Yerry Mina, Ben Godfrey, Séamu...","[Daniel Iversen, Çaglar Söyüncü, Jannik Vester...","[Tom Heaton, Lisandro Martínez, Tyrell Malacia...","[Thomas Strakosha, Mads Bech Sørensen, Tristan...","[Jason Steele, Jan Paul van Hecke, Joël Veltma...","[Fraser Forster, Davinson Sánchez, Emerson Roy...","[Wayne Hennessey, Steve Cook, Neco Williams, H...","[Alphonse Aréola, Ben Johnson, Thilo Kehrer, N...","[Adrián, Joe Gomez, Ibrahima Konaté, Konstanti...",...,"[Martin Dúbravka, Paul Dummett, Jamaal Lascell...","[Wayne Hennessey, Felipe, Joe Worrall, Serge A...","[Fraser Forster, Pedro Porro, Davinson Sánchez...","[Marcus Bettinelli, Trevoh Chalobah, Ben Chilw...","[Asmir Begovic, Mason Holgate, Yerry Mina, Ben...","[Robin Olsen, Viljami Sinisalo, Matty Cash, Ál...","[Matthew Cox, Zanka, Kristoffer Ajer, Mads Roe...","[Jason Steele, Adam Webster, Jan Paul van Heck...","[Tom Heaton, Victor Lindelöf, Harry Maguire, T...","[Daniel Bentley, Nathan Collins, Jonny, Hugo B..."
team1_stat,"{'possession_%': '66.8', 'shots_on_target': '4...","{'possession_%': '48.9', 'shots_on_target': '4...","{'possession_%': '61.2', 'shots_on_target': '6...","{'possession_%': '58.5', 'shots_on_target': '6...","{'possession_%': '27', 'shots_on_target': '7',...","{'possession_%': '67.8', 'shots_on_target': '5...","{'possession_%': '59.3', 'shots_on_target': '2...","{'possession_%': '27.7', 'shots_on_target': '5...","{'possession_%': 'West', 'shots_on_target': '6...","{'possession_%': '57', 'shots_on_target': '5',...",...,"{'possession_%': '62.7', 'shots_on_target': '2...","{'possession_%': '30.1', 'shots_on_target': '2...","{'possession_%': '3', 'shots_on_target': '12',...","{'possession_%': '66.9', 'shots_on_target': '3...","{'possession_%': '29.5', 'shots_on_target': '4...","{'possession_%': '63.2', 'shots_on_target': '4...","{'possession_%': '48.3', 'shots_on_target': '4...","{'possession_%': '71.8', 'shots_on_target': '6...","{'possession_%': '5', 'shots_on_target': '14',...","{'possession_%': '41.8', 'shots_on_target': '6..."
team2_name,Newcastle United,Brighton and Hove Albion,Fulham,Bournemouth,Liverpool,Arsenal,Aston Villa,Chelsea,Brentford,Leicester City,...,West Ham United,Leeds United,Manchester City,Fulham,Arsenal,Leicester City,Southampton,Bournemouth,Crystal Palace,Liverpool
team2_startings,"[Nick Pope, Kieran Trippier, Sven Botman, Fabi...","[Robert Sánchez, Lewis Dunk, Levi Colwill, Per...","[Bernd Leno, Kenny Tete, Tosin Adarabioyo, Tim...","[Mark Travers, Lloyd Kelly, Chris Mepham, Adam...","[Alisson, Virgil van Dijk, Ibrahima Konaté, Ko...","[Aaron Ramsdale, Ben White, Gabriel Magalhães,...","[Robin Olsen, Ezri Konsa, Tyrone Mings, Ashley...","[Kepa Arrizabalaga, Thiago Silva, Kalidou Koul...","[David Raya, Ethan Pinnock, Zanka, Ben Mee, Ri...","[Danny Ward, Wout Faes, Daniel Amartey, Timoth...",...,"[Lukasz Fabianski, Angelo Ogbonna, Thilo Kehre...","[Illan Meslier, Luke Ayling, Liam Cooper, Pasc...","[Ederson, Kyle Walker, Nathan Aké, Manuel Akan...","[Bernd Leno, Kenny Tete, Tim Ream, Issa Diop, ...","[Aaron Ramsdale, Ben White, Gabriel Magalhães,...","[Danny Ward, Wout Faes, Harry Souttar, Victor ...","[Gavin Bazunu, James Bree, Romain Perraud, Moh...","[Neto, Chris Mepham, Adam Smith, Marcos Senesi...","[Vicente Guaita, Tyrick Mitchell, Marc Guéhi, ...","[Alisson, Joe Gomez, Andrew Robertson, Joël Ma..."
team2_subs,"[Martin Dúbravka, Jamaal Lascelles, Jamal Lewi...","[Jason Steele, Tariq Lamptey, Jan Paul van Hec...","[Marek Rodák, Layvin Kurzawa, Issa Diop, Harry...","[Cameron Plain, Jack Stephens, Jack Stacey, Jo...","[Caoimhín Kelleher, Joe Gomez, Andrew Robertso...","[Matt Turner, Kieran Tierney, Rob Holding, Céd...","[Emiliano Martínez, Matty Cash, Calum Chambers...","[Marcus Bettinelli, Trevoh Chalobah, Mateo Kov...","[Matthew Cox, Pontus Jansson, Yoane Wissa, Mik...","[Daniel Iversen, Çaglar Söyüncü, Jannik Vester...",...,"[Krisztián Hegyi, Joseph Anang, Ben Johnson, A...","[Joel Robles, Junior Firpo, Rasmus Kristensen,...","[Stefan Ortega, Rúben Dias, Aymeric Laporte, M...","[Marek Rodák, Layvin Kurzawa, Tosin Adarabioyo...","[Matt Turner, Kieran Tierney, Jakub Kiwior, Ro...","[Daniel Iversen, Çaglar Söyüncü, Luke Thomas, ...","[Willy Caballero, Lyanco, Kamaldeen Sulemana, ...","[Mark Travers, Matías Viña, Jack Stacey, Ben G...","[Sam Johnstone, Joe Whitworth, James Tomkins, ...","[Caoimhín Kelleher, Konstantinos Tsimikas, Nat..."
team2_stat,"{'possession_%': '33.2', 'shots_on_target': '1...","{'possession_%': '51.1', 'shots_on_target': '8...","{'possession_%': '38.8', 'shots_on_target': '2...","{'possession_%': '41.5', 'shots_on_target': '4...","{'possession_%': '73', 'shots_on_target': '6',...","{'possession_%': '32.2', 'shots_on_target': '7...","{'possession_%': '40.7', 'shots_on_target': '4...","{'possession_%': '72.3', 'shots_on_target': '2...","{'possession_%': 'Brentford', 'shots_on_target...","{'possession_%': '43', 'shots_on_target': '2',...",...,"{'possession_%': '37.3', 'shots_on_target': '1...","{'possession_%': '69.9', 'shots_on_target': '4...","{'possession_%': '5', 'shots_on_target': '15',...","{'possession_%': '33.1', 'shots_on_target': '4...","{'possession_%': '70.5', 'shots_on_target': '3...","{'possession_%': '36.8', 'shots_on_target': '5...","{'possession_%': '51.7', 'shots_on_target': '6...","{'possession_%': '28.2', 'shots_on_target': '2...","{'possession_%': '3', 'shots_on_target': '10',...","{'possession_%': '58.2', 'shots_on_target': '4..."

In [8]:
df = df.T
df.head()

,event,matchweek,team1_name,team1_startings,team1_subs,team1_stat,team2_name,team2_startings,team2_subs,team2_stat
75091,"[Full-time Match ends, Arsenal 0, Newcastle Un...",Matchweek 19,Arsenal,"[Aaron Ramsdale, Ben White, Gabriel Magalhães,...","[Matt Turner, Kieran Tierney, Rob Holding, Tak...","{'possession_%': '66.8', 'shots_on_target': '4...",Newcastle United,"[Nick Pope, Kieran Trippier, Sven Botman, Fabi...","[Martin Dúbravka, Jamaal Lascelles, Jamal Lewi...","{'possession_%': '33.2', 'shots_on_target': '1..."
75096,"[Full-time Match ends, Everton 1, Brighton and...",Matchweek 19,Everton,"[Jordan Pickford, James Tarkowski, Nathan Patt...","[Asmir Begovic, Yerry Mina, Ben Godfrey, Séamu...","{'possession_%': '48.9', 'shots_on_target': '4...",Brighton and Hove Albion,"[Robert Sánchez, Lewis Dunk, Levi Colwill, Per...","[Jason Steele, Tariq Lamptey, Jan Paul van Hec...","{'possession_%': '51.1', 'shots_on_target': '8..."
75098,"[Full-time Match ends, Leicester City 0, Fulha...",Matchweek 19,Leicester City,"[Danny Ward, Wout Faes, Daniel Amartey, Timoth...","[Daniel Iversen, Çaglar Söyüncü, Jannik Vester...","{'possession_%': '61.2', 'shots_on_target': '6...",Fulham,"[Bernd Leno, Kenny Tete, Tosin Adarabioyo, Tim...","[Marek Rodák, Layvin Kurzawa, Issa Diop, Harry...","{'possession_%': '38.8', 'shots_on_target': '2..."
75099,"[Full-time Match ends, Manchester United 3, Bo...",Matchweek 19,Manchester United,"[David de Gea, Victor Lindelöf, Harry Maguire,...","[Tom Heaton, Lisandro Martínez, Tyrell Malacia...","{'possession_%': '58.5', 'shots_on_target': '6...",Bournemouth,"[Mark Travers, Lloyd Kelly, Chris Mepham, Adam...","[Cameron Plain, Jack Stephens, Jack Stacey, Jo...","{'possession_%': '41.5', 'shots_on_target': '4..."
75093,"[Full-time Match ends, Brentford 3, Liverpool ...",Matchweek 19,Brentford,"[David Raya, Ethan Pinnock, Zanka, Ben Mee, Ri...","[Thomas Strakosha, Mads Bech Sørensen, Tristan...","{'possession_%': '27', 'shots_on_target': '7',...",Liverpool,"[Alisson, Virgil van Dijk, Ibrahima Konaté, Ko...","[Caoimhín Kelleher, Joe Gomez, Andrew Robertso...","{'possession_%': '73', 'shots_on_target': '6',..."

In [14]:
team1_stats = df['team1_stat'].apply(pd.Series)
team1_stats = team1_stats.add_prefix('team1_')
team1_stats.head()

,team1_possession_%,team1_shots_on_target,team1_shots,team1_touches,team1_passes,team1_tackels,team1_clearances,team1_corners,team1_offsides,team1_yellow_cards,team1_foul_conceded
75091,66.8,4,17,703,536,13,17,5,1,4,10
75096,48.9,4,10,663,478,16,15,5,1,3,8
75098,61.2,6,15,732,551,17,15,6,0,2,12
75099,58.5,6,18,731,579,9,11,6,0,0,13
75093,27,7,10,432,237,17,37,4,7,1,5

In [15]:
team2_stats = df['team2_stat'].apply(pd.Series)
team2_stats = team2_stats.add_prefix('team2_')
team2_stats.head()

,team2_possession_%,team2_shots_on_target,team2_shots,team2_touches,team2_passes,team2_tackels,team2_clearances,team2_corners,team2_offsides,team2_yellow_cards,team2_foul_conceded
75091,33.2,1,8,446,253,23,29,5,4,5,16
75096,51.1,8,19,676,512,16,13,2,0,1,10
75098,38.8,2,11,566,348,13,32,3,1,6,11
75099,41.5,4,7,579,406,18,19,5,2,3,7
75093,73,6,16,857,652,9,15,9,4,3,8

In [16]:
df = pd.concat([df, team1_stats, team2_stats], axis=1)
df.drop(['team1_stat', 'team2_stat'], axis=1, inplace=True)

df.head()

,event,matchweek,team1_name,team1_startings,team1_subs,team2_name,team2_startings,team2_subs,team1_possession_%,team1_shots_on_target,...,team2_shots_on_target,team2_shots,team2_touches,team2_passes,team2_tackels,team2_clearances,team2_corners,team2_offsides,team2_yellow_cards,team2_foul_conceded
75091,"[Full-time Match ends, Arsenal 0, Newcastle Un...",Matchweek 19,Arsenal,"[Aaron Ramsdale, Ben White, Gabriel Magalhães,...","[Matt Turner, Kieran Tierney, Rob Holding, Tak...",Newcastle United,"[Nick Pope, Kieran Trippier, Sven Botman, Fabi...","[Martin Dúbravka, Jamaal Lascelles, Jamal Lewi...",66.8,4,...,1,8,446,253,23,29,5,4,5,16
75096,"[Full-time Match ends, Everton 1, Brighton and...",Matchweek 19,Everton,"[Jordan Pickford, James Tarkowski, Nathan Patt...","[Asmir Begovic, Yerry Mina, Ben Godfrey, Séamu...",Brighton and Hove Albion,"[Robert Sánchez, Lewis Dunk, Levi Colwill, Per...","[Jason Steele, Tariq Lamptey, Jan Paul van Hec...",48.9,4,...,8,19,676,512,16,13,2,0,1,10
75098,"[Full-time Match ends, Leicester City 0, Fulha...",Matchweek 19,Leicester City,"[Danny Ward, Wout Faes, Daniel Amartey, Timoth...","[Daniel Iversen, Çaglar Söyüncü, Jannik Vester...",Fulham,"[Bernd Leno, Kenny Tete, Tosin Adarabioyo, Tim...","[Marek Rodák, Layvin Kurzawa, Issa Diop, Harry...",61.2,6,...,2,11,566,348,13,32,3,1,6,11
75099,"[Full-time Match ends, Manchester United 3, Bo...",Matchweek 19,Manchester United,"[David de Gea, Victor Lindelöf, Harry Maguire,...","[Tom Heaton, Lisandro Martínez, Tyrell Malacia...",Bournemouth,"[Mark Travers, Lloyd Kelly, Chris Mepham, Adam...","[Cameron Plain, Jack Stephens, Jack Stacey, Jo...",58.5,6,...,4,7,579,406,18,19,5,2,3,7
75093,"[Full-time Match ends, Brentford 3, Liverpool ...",Matchweek 19,Brentford,"[David Raya, Ethan Pinnock, Zanka, Ben Mee, Ri...","[Thomas Strakosha, Mads Bech Sørensen, Tristan...",Liverpool,"[Alisson, Virgil van Dijk, Ibrahima Konaté, Ko...","[Caoimhín Kelleher, Joe Gomez, Andrew Robertso...",27,7,...,6,16,857,652,9,15,9,4,3,8

In [17]:
df = df.reset_index()
df.rename(columns={'index': 'match_id'}, inplace=True)

df.head()

,match_id,event,matchweek,team1_name,team1_startings,team1_subs,team2_name,team2_startings,team2_subs,team1_possession_%,...,team2_shots_on_target,team2_shots,team2_touches,team2_passes,team2_tackels,team2_clearances,team2_corners,team2_offsides,team2_yellow_cards,team2_foul_conceded
0,75091,"[Full-time Match ends, Arsenal 0, Newcastle Un...",Matchweek 19,Arsenal,"[Aaron Ramsdale, Ben White, Gabriel Magalhães,...","[Matt Turner, Kieran Tierney, Rob Holding, Tak...",Newcastle United,"[Nick Pope, Kieran Trippier, Sven Botman, Fabi...","[Martin Dúbravka, Jamaal Lascelles, Jamal Lewi...",66.8,...,1,8,446,253,23,29,5,4,5,16
1,75096,"[Full-time Match ends, Everton 1, Brighton and...",Matchweek 19,Everton,"[Jordan Pickford, James Tarkowski, Nathan Patt...","[Asmir Begovic, Yerry Mina, Ben Godfrey, Séamu...",Brighton and Hove Albion,"[Robert Sánchez, Lewis Dunk, Levi Colwill, Per...","[Jason Steele, Tariq Lamptey, Jan Paul van Hec...",48.9,...,8,19,676,512,16,13,2,0,1,10
2,75098,"[Full-time Match ends, Leicester City 0, Fulha...",Matchweek 19,Leicester City,"[Danny Ward, Wout Faes, Daniel Amartey, Timoth...","[Daniel Iversen, Çaglar Söyüncü, Jannik Vester...",Fulham,"[Bernd Leno, Kenny Tete, Tosin Adarabioyo, Tim...","[Marek Rodák, Layvin Kurzawa, Issa Diop, Harry...",61.2,...,2,11,566,348,13,32,3,1,6,11
3,75099,"[Full-time Match ends, Manchester United 3, Bo...",Matchweek 19,Manchester United,"[David de Gea, Victor Lindelöf, Harry Maguire,...","[Tom Heaton, Lisandro Martínez, Tyrell Malacia...",Bournemouth,"[Mark Travers, Lloyd Kelly, Chris Mepham, Adam...","[Cameron Plain, Jack Stephens, Jack Stacey, Jo...",58.5,...,4,7,579,406,18,19,5,2,3,7
4,75093,"[Full-time Match ends, Brentford 3, Liverpool ...",Matchweek 19,Brentford,"[David Raya, Ethan Pinnock, Zanka, Ben Mee, Ri...","[Thomas Strakosha, Mads Bech Sørensen, Tristan...",Liverpool,"[Alisson, Virgil van Dijk, Ibrahima Konaté, Ko...","[Caoimhín Kelleher, Joe Gomez, Andrew Robertso...",27,...,6,16,857,652,9,15,9,4,3,8

In [38]:
df['event_clean'] = df['event'].astype(str).str.replace('[', '', regex=False).str.replace(']', '', regex=False)

In [39]:
parts = df['event_clean'].str.split(',')

df['team1_goals'] = parts.str[1].str.extract('(\d+)')
df['team2_goals'] = parts.str[2].str.extract('(\d+)')

df['team1_goals'] = pd.to_numeric(df['team1_goals'], errors='coerce')
df['team2_goals'] = pd.to_numeric(df['team2_goals'], errors='coerce')

In [40]:
df[['event_clean', 'team1_goals', 'team2_goals']].head(10)

                                         event_clean  team1_goals  team2_goals
0  'Full-time Match ends, Arsenal 0, Newcastle Un...            0            0
1  'Full-time Match ends, Everton 1, Brighton and...            1            4
2  'Full-time Match ends, Leicester City 0, Fulha...            0            1
3  'Full-time Match ends, Manchester United 3, Bo...            3            0
4  'Full-time Match ends, Brentford 3, Liverpool ...            3            1
5  'Full-time Match ends, Brighton and Hove Albio...            2            4
6  'Full-time Match ends, Tottenham Hotspur 0, As...            0            2
7  'Full-time Match ends, Nottingham Forest 1, Ch...            1            1
8  'Full-time Match ends, West Ham United 0, Bren...            0            2
9  'Full-time Match ends, Liverpool 2, Leicester ...            2            1

In [47]:
def get_result(row):
    if row['team1_goals'] > row['team2_goals']:
        return 'Home Win'
    elif row['team1_goals'] < row['team2_goals']:
        return 'Away Win'
    else:
        return 'Draw'

df['result'] = df.apply(get_result, axis=1)

In [48]:
def team1_points(row):
    if row['result'] == 'Home Win':
        return 3
    elif row['result'] == 'Draw':
        return 1
    else:
        return 0

def team2_points(row):
    if row['result'] == 'Away Win':
        return 3
    elif row['result'] == 'Draw':
        return 1
    else:
        return 0

df['team1_points'] = df.apply(team1_points, axis=1)
df['team2_points'] = df.apply(team2_points, axis=1)

In [49]:
df['goal_diff'] = df['team1_goals'] - df['team2_goals']

In [50]:
df[['team1_name', 'team2_name', 'team1_goals', 'team2_goals', 'result', 'team1_points', 'team2_points']].head(10)

,team1_name,team2_name,team1_goals,team2_goals,result,team1_points,team2_points
0,Arsenal,Newcastle United,0,0,Draw,1,1
1,Everton,Brighton and Hove Albion,1,4,Away Win,0,3
2,Leicester City,Fulham,0,1,Away Win,0,3
3,Manchester United,Bournemouth,3,0,Home Win,3,0
4,Brentford,Liverpool,3,1,Home Win,3,0
5,Brighton and Hove Albion,Arsenal,2,4,Away Win,0,3
6,Tottenham Hotspur,Aston Villa,0,2,Away Win,0,3
7,Nottingham Forest,Chelsea,1,1,Draw,1,1
8,West Ham United,Brentford,0,2,Away Win,0,3
9,Liverpool,Leicester City,2,1,Home Win,3,0

In [51]:
team1_df = df[['team1_name', 'team1_goals', 'team2_goals', 'team1_points']].copy()

team1_df.columns = ['team', 'goals_scored', 'goals_conceded', 'points']

In [52]:
team2_df = df[['team2_name', 'team2_goals', 'team1_goals', 'team2_points']].copy()

team2_df.columns = ['team', 'goals_scored', 'goals_conceded', 'points']

In [53]:
league_df = pd.concat([team1_df, team2_df])

In [54]:
league_table = league_df.groupby('team').sum().reset_index()

In [55]:
league_table = league_table.sort_values(by='points', ascending=False)

In [57]:
league_table.head(10)

                        team  goals_scored  goals_conceded  points
0                    Arsenal            45              17      50
13           Manchester City            53              21      45
14         Manchester United            34              26      42
15          Newcastle United            34              12      40
18         Tottenham Hotspur            41              31      39
3                  Brentford            35              28      33
9                     Fulham            32              30      32
5   Brighton and Hove Albion            35              25      30
6                    Chelsea            22              21      30
12                 Liverpool            34              28      29

In [58]:
league_table['goal_diff'] = league_table['goals_scored'] - league_table['goals_conceded']

In [59]:
league_table.head(10)

                        team  goals_scored  goals_conceded  points  goal_diff
0                    Arsenal            45              17      50         28
13           Manchester City            53              21      45         32
14         Manchester United            34              26      42          8
15          Newcastle United            34              12      40         22
18         Tottenham Hotspur            41              31      39         10
3                  Brentford            35              28      33          7
9                     Fulham            32              30      32          2
5   Brighton and Hove Albion            35              25      30         10
6                    Chelsea            22              21      30          1
12                 Liverpool            34              28      29          6

In [62]:
league_table.head(20)

,team,goals_scored,goals_conceded,points,goal_diff,rank
0,Arsenal,45,17,50,28,1
1,Manchester City,53,21,45,32,2
2,Manchester United,34,26,42,8,3
3,Newcastle United,34,12,40,22,4
4,Tottenham Hotspur,41,31,39,10,5
5,Brentford,35,28,33,7,6
6,Fulham,32,30,32,2,7
7,Brighton and Hove Albion,35,25,30,10,8
8,Chelsea,22,21,30,1,9
9,Liverpool,34,28,29,6,10
10,Aston Villa,25,31,28,-6,11
11,Nottingham Forest,17,35,24,-18,12
12,Crystal Palace,19,29,24,-10,13
13,Leicester City,32,37,21,-5,14
14,Wolverhampton Wanderers,15,30,20,-15,15
15,West Ham United,18,26,19,-8,16
16,Everton,16,28,18,-12,17
17,Leeds United,26,34,18,-8,18
18,Bournemouth,19,43,17,-24,19
19,Southampton,17,38,15,-21,20

In [63]:
league_table = league_table.sort_values(by=['points', 'goal_diff'], ascending=False)

In [64]:
league_table = league_table.reset_index(drop=True)

In [65]:
league_table['rank'] = league_table.index + 1

In [66]:
league_table.head(20)

,team,goals_scored,goals_conceded,points,goal_diff,rank
0,Arsenal,45,17,50,28,1
1,Manchester City,53,21,45,32,2
2,Manchester United,34,26,42,8,3
3,Newcastle United,34,12,40,22,4
4,Tottenham Hotspur,41,31,39,10,5
5,Brentford,35,28,33,7,6
6,Fulham,32,30,32,2,7
7,Brighton and Hove Albion,35,25,30,10,8
8,Chelsea,22,21,30,1,9
9,Liverpool,34,28,29,6,10
10,Aston Villa,25,31,28,-6,11
11,Crystal Palace,19,29,24,-10,12
12,Nottingham Forest,17,35,24,-18,13
13,Leicester City,32,37,21,-5,14
14,Wolverhampton Wanderers,15,30,20,-15,15
15,West Ham United,18,26,19,-8,16
16,Leeds United,26,34,18,-8,17
17,Everton,16,28,18,-12,18
18,Bournemouth,19,43,17,-24,19
19,Southampton,17,38,15,-21,20

In [67]:
league_table.to_csv('league_table.csv', index=False)